Algoritmo "volume_do_paralelipipedo"
// Descrição   : volume do paralelipipedo
// Autor(a)    : joao sousa
// Data atual  : 14/09/2017
Var
 comprimento,largura,altura,volume :real
Inicio
 escreva("Qual a largura")
 leia(largura)
 escreva("Qual o comprimento")
 leia(comprimento)
 escreva("Qual a altura")
 leia(altura)

 volume <- largura * comprimento * altura
 escreva("O volume é",volume)
Fimalgoritmo